:toc:
:toc-placement!:
:toclevels: 4
toc::[]

WARNING: *This guid is work in progress!*

== Advanced Guide

IMPORTANT: The setup of Vagrant, VirtualBox and SSH is not part of this documentation. +
Please follow the link:../vagrant.adoc[documentation].

=== Overview

:puml: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/Rendanic/ansible-oracle/tbrdoc/doc

image::{puml}/guides/advanced.puml[Architecturview]

.Used defaults in this guide
[options="header,footer"]
|=======================
|Value |Description
|~/git/ansible-oracle |git Repository on Host System
|~/git/ansible-oracle |git Repository in VM
|~/.ssh/id_rsa |private Key on Host System
|vagrant |SSH-User for Login and Ansible
|~/git/ansible-oracle/ansible-oracle/example/beginner|Vagrantfile location
|=======================


=== Oracle Installation media and Patches

IMPORTANT: It is highly recommended to use the following structure. +
Do not change this until you really know what you are doing.

All installation medias are searched in `oracle_stage_remote` on the database server.

WARNING: It is assumend that `oracle_stage_remote` is set to `/sw`

==== Installation media

IMPORTANT: Only `LINUX.X64_193000_db_home.zip` is needed as base media for the _Advanced Guide_.

.Example `oracle_stage_remote: /sw`
----
/sw/LINUX.X64_180000_db_home.zip
/sw/LINUX.X64_193000_grid_home.zip
/sw/LINUX.X64_213000_grid_home.zip
/sw/LINUX.X64_193000_db_home.zip
/sw/LINUX.X64_213000_db_home.zip
----

==== Patches OPatch archive

IMPORTANT: Only `p6880880_190000_Linux-x86-64.zip` is needed for patching in the _Advanced Guide_.

.Example `oracle_stage_remote: /sw` for OPatch
----
/sw/oracle/linux64/p6880880_112000_Linux-x86-64.zip
/sw/oracle/linux64/p6880880_180000_Linux-x86-64.zip
/sw/oracle/linux64/p6880880_190000_Linux-x86-64.zip
/sw/oracle/linux64/p6880880_210000_Linux-x86-64.zip
----

==== Patch structure

<todo wip>

[options="header,footer"]
|=======================
|Directory |Description
|=======================

=== Prepare Host System

IMPORTANT: All steps are executed on the Host System inside a `git+bash`.

.clone git Repository
----
mkdir ~/git
cd ~/git

git clone https://github.com/oravirt/ansible-oracle.git
----

==== Configure SSH-Key

IMPORTANT: Do not skip the preparation for Vagrant and SSH. +
Please follow the link:../vagrant.adoc[documentation].

.Copy Public key into Vagrantfile directories
----
cp ~/.ssh/id_rsa.pub ~/git/ansible-oracle/ansible-oracle/example/advanced/vagrant/ansible/
cp ~/.ssh/id_rsa.pub ~/git/ansible-oracle/ansible-oracle/example/advanced/vagrant/dbfs161/
----

.Start ssh-Agent
----
eval $(ssh-agent)
----

.Import the generated key
----
ssh-add ~/.ssh/id_rsa
----

=== Ansible-Controller

==== Start Vagrantbox

IMPORTANT: The Deployment und provisioning of the VM takes some minutes. +
It highly depends on the speed of the internet connection.

IMPORTANT: The SSH public key is configured during the provisioning phase of the VM. +
*Do not forget to copy the file before starting the box with `vagrant up`.*

.vagrant up
----
cd ~/git/ansible-oracle/ansible-oracle/example/advanced/vagrant/ansible
VAGRANT_EXPERIMENTAL=disks vagrant up
----

==== Connect to VM

IMPORTANT: All furter steps are done inside the VM. +
The SSH-Setup from previous chapter must be completed before!


.Test connection with ssh in `git+bash`
----
ssh -A vagrant@192.168.56.160
exit
----

VSCode will open the connection to the target and mount the home automatically, when started with a workspacefile.

.Open RemoteSSH Session with Visual Studio Code
----
code example/advanced/vscode/advanced.code-workspace
----

==== Start Ansible-Container inside VM

.Start Ansible-Container
----
cd ~/git/ansible-oracle/docker
docker-compose run --rm -w /git/ansible-oracle/example/beginner/ansible ansible bash
----

.Example
[auote, output]
----
[vagrant@beginner-dbfs-151-192-168-56-161 docker]$ docker-compose run --rm -w /git/ansible-oracle/example/beginner/ansible ansible bash
[+] Running 2/0
 ⠿ Network docker_default          Created
 ⠿ Volume "docker_ansible_galaxy"  Created

ansible@ansible-oracle:/git/ansible-oracle/example/beginner/ansible$
----


IMPORTANT: The collection are installed once and stored on the docker volume.

.Install Collections
----
ansible@ansible-oracle:/git/ansible-oracle/example/beginner/ansible$ ansible-galaxy collection install -r requirements.yml
----

.Example
[auote, output]
----
ansible@ansible-oracle:/git/ansible-oracle/example/beginner/ansible$ ansible-galaxy collection install -r requirements.yml 
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/devsec-hardening-8.2.0.tar.gz to /home/ansible/.ansible/tmp/ansible-local-25z8isd809/tmp25w_hn4o/devsec-hardening-8.2.0-0j9481f1
Installing 'devsec.hardening:8.2.0' to '/ansible/galaxy/ansible_collections/devsec/hardening'
Downloading https://galaxy.ansible.com/download/opitzconsulting-ansible_oracle-3.2.0.tar.gz to /home/ansible/.ansible/tmp/ansible-local-25z8isd809/tmp25w_hn4o/opitzconsulting-ansible_oracle-3.2.0-x3wo4c3b
devsec.hardening:8.2.0 was installed successfully
Installing 'opitzconsulting.ansible_oracle:3.2.0' to '/ansible/galaxy/ansible_collections/opitzconsulting/ansible_oracle'
Downloading https://galaxy.ansible.com/download/ansible-posix-1.4.0.tar.gz to /home/ansible/.ansible/tmp/ansible-local-25z8isd809/tmp25w_hn4o/ansible-posix-1.4.0-1jub71c6
opitzconsulting.ansible_oracle:3.2.0 was installed successfully
Installing 'ansible.posix:1.4.0' to '/ansible/galaxy/ansible_collections/ansible/posix'
Downloading https://galaxy.ansible.com/download/community-mysql-3.5.1.tar.gz to /home/ansible/.ansible/tmp/ansible-local-25z8isd809/tmp25w_hn4o/community-mysql-3.5.1-lkcnbkd5
ansible.posix:1.4.0 was installed successfully
Installing 'community.mysql:3.5.1' to '/ansible/galaxy/ansible_collections/community/mysql'
Downloading https://galaxy.ansible.com/download/community-crypto-2.8.0.tar.gz to /home/ansible/.ansible/tmp/ansible-local-25z8isd809/tmp25w_hn4o/community-crypto-2.8.0-6sco_75m
community.mysql:3.5.1 was installed successfully
Installing 'community.crypto:2.8.0' to '/ansible/galaxy/ansible_collections/community/crypto'
Downloading https://galaxy.ansible.com/download/community-general-5.8.0.tar.gz to /home/ansible/.ansible/tmp/ansible-local-25z8isd809/tmp25w_hn4o/community-general-5.8.0-up2j_3iq
community.crypto:2.8.0 was installed successfully
Installing 'community.general:5.8.0' to '/ansible/galaxy/ansible_collections/community/general'
community.general:5.8.0 was installed successfully
----
