---
# Configure systemd only for Single-Instance without GI/Restart
- name: install_home_db | Configure oracle-rdbms auto-startup service (systemd.d)
  ansible.builtin.template:
    src: oracle-rdbms-service.j2
    dest: /etc/systemd/system/oracle-rdbms.service
    owner: root
    mode: "0644"
  become: true
  become_user: root
  notify:
    - systemd register and reload
  with_items: "{{ db_homes_installed }}"
  when:
    - autostartup_service
    - oracle_install_option_gi | default('') | length == 0
    - hostinitdaemon == "systemd"
    - item.state | lower == 'present'
  tags:
    - autostartup_service
    - seclimit    # Update template when ulimits have been chagned as well.
