- debug: 
    msg: "{{ listener_name_template }} : {{ oracle_home_db }} {{ oracle_netca_rsp }}"
  when: create_listener

- name: listener | Create responsefile for listener configuration
  template: src=netca.rsp.{{ dbh.oracle_version_db }}.j2 dest={{ oracle_rsp_stage }}/{{ oracle_netca_rsp }}
  become: true
  become_user: "{{ oracle_user }}"
  when: create_listener
  tags: responsefile_netca, listener_install

- name: listener | Create listener
  shell: "{{ oracle_home_db }}/bin/netca -responseFile {{ oracle_rsp_stage }}/{{ oracle_netca_rsp }} -silent"
  args:
      creates: "{{ oracle_home_db }}/network/admin/listener.ora"
  become: true
  become_user: "{{ oracle_user }}"
  when: create_listener
  tags: listener_install
