---
collections:
  - name: opitzconsulting.ansible_oracle
    version: 4.14.0
  - name: community.general
    version: ">=8.0.0,<9.0.0"

  # following entry is for development only!
  # - name: opitzconsulting.ansible_oracle
  #   source: ./../../..
  #   type: dir

  # - name: https://github.com/Rendanic/ansible-oracle.git
  #   type: git
  #   version: workflow
