---
- name: Include Assert
  ansible.builtin.include_tasks: assert.yml
  tags: always

- name: Execute under root
  become: true
  become_user: root
  block:
    - name: Configure repository on OracleLinux
      ansible.builtin.yum_repository:
        name: ol7_oracle_software
        description: ol7_oracle_software
        file: external_repos
        baseurl: "{{ ords_ol7_reposiory }}"
        gpgcheck: false

    - name: Install ORDS with yum
      ansible.builtin.yum:
        name: ords
        state: present

    - name: Create directories for ORDS
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        owner: oracle
        mode: "0755"
      with_items:
        - "{{ oraswords_meta_ords_config }}"

    - name: Include Configure ORDS
      ansible.builtin.include_tasks: configure_ords.yml
      tags:
        - always
