---
galaxy_info:
  role_name: oraswahf_install
  author: Thorsten Bruhns
  description: Install Autonomous Health Framework from Oracle
  company: Thorsten Bruhns

  license: license (MIT)

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8

  galaxy_tags:
    - ahf
    - oracle

dependencies:
  - role: orahost_meta
  - role: orasw-meta
