---
# @meta description: >
#
# Meta role used by other roles to share variable defaults
#
# This role is needed for _oraswords_install_.
#
# This role has a dependency to `orahost_meta`.
#
# @end
#
# @meta author: [Thorsten Bruhns]
galaxy_info:
  role_name: oraswords_meta
  author: Thorsten Bruhns
  description: meta role used by other roles to share variable defaults.
  company: Thorsten Bruhns
  license: license (MIT)

  min_ansible_version: 2.14.0

  platforms:
    - name: EL
      versions:
        - "7"
        - "8"

  galaxy_tags: []

dependencies: []
