---
# Note about memory assert check
# opatch apply may fail when <4gB virtual memory is availible.
# We need to check for free space with free+swap, because Hugepages
# are not useable for opatch!
- name: assert free+swap Memory
  ansible.builtin.assert:
    quiet: true
    that:
      - ansible_memory_mb.real.free + ansible_memory_mb.swap.free > 4096
    fail_msg: >-
      Make sure that free Memory + free swap is > 4096MB.
      Found {{ ansible_memory_mb.real.free + ansible_memory_mb.swap.free }}MB
  tags:
    - always
    - assert_memory
